<div>
	<a href="/" class="logo">
        <img border="0" src="<?php echo Zend_Registry::get("contextPath"); ?>/public/images/logo.gif">
    </a>
</div>
<br>
<hr/>
<div>
<form><input type="button" value=" Print this page "
onclick="window.print();return false;" /></form> 
<h2>Terms of Service</h2>
<p>Date  of Last Revision: July 5, 2008<br />
<strong>ABOUT  GOALFACE</strong><br />
  Welcome  to GoalFace, an online football community, conversational media and social  networking service.�� The GoalFace  service and network (collectively, &quot;GoalFace&quot; or &quot;the  service&quot; or �Web site� or �site�) are operated by GoalFace, Inc., and its  corporate affiliates (collectively, &quot;us&quot;, &quot;we&quot; or &quot;the  Company&quot;). GoalFace allows Members to create personal profiles to submit,  rank, comment on and share their thoughts and opinions on the latest in global  football while connecting with friends, teams and fans from around the  world.� <br />
  GoalFace  is available to you whether or not you are a &quot;member&quot;.� Both &quot;visitors&quot; and  &quot;members&quot; are subject to the following Terms of Service (�Terms of  Service�, &quot;TOS&quot; or �Agreement�).�  By accessing or using our Web site, and/or any pages thereof at <a href="http://www.goalface.com/">www.GoalFace.com</a> by personal computer, mobile device or  any other means electronic (together the &quot;site&quot;) or by posting a  Share Button on your site, you (the &quot;User&quot;) signify that you have  read, understand and agree to be bound by these TOS, whether or not you are a  registered member of GoalFace. We reserve the right, at our sole discretion, to  change, modify, add, or delete portions of these Terms of Service at any time  without further notice. If we do this, we will post the changes to these Terms  of Service on this page and will indicate the date these terms were last  revised. Your continued use of the service or the site after any such changes  constitutes your acceptance of the new Terms of Service. If you do not agree to  abide by these or any future Terms of Service, do not use or access (or  continue to use or access) the service or the site. Account terminiation  requests can be made by e-mailing the <a href="mailto:CommunityMgr@goalface.com">GoalFace community manager.</a> It is your  responsibility to regularly check the site to determine if there have been  changes to these Terms of Service and to review such changes.</p>
<h2>Eligibility</h2>
<p>Membership  in the service is void where prohibited. <strong>This site is intended solely for  users who are thirteen (13) years of age or older. If you are under 13 years of  age, please do not attempt to register for GoalFace or send any information  about yourself to us.</strong> We recommend that minors (13 � 17 years of age) over  the age of 13 ask their parents for permission before registering with  GoalFace. Any registration by, use of or access to the site by anyone under 13  is unauthorized, unlicensed and in violation of these Terms of Service. By  using the service or the site, you represent and warrant that you are 13 or  older and that you agree to and to abide by all of the terms and conditions of  this agreement.� In consideration of your  use of the service, you also represent that you are of legal age to form a  binding contract and are not a person barred from receiving services under the  laws of the United States  or other applicable jurisdiction. International users  agree to comply with all local rules regarding online conduct and acceptable  content, including laws regulating the export of data from the United States  or your country of residence. You are solely responsible for your conduct and  any data, text, information, photos, video, links and other content  (&quot;materials&quot;) that you submit, post, and display on this service. By using the  site, you represent and warrant that you have the right, authority, and  capacity to enter into these Terms of Service and will abide by such Terms of  Service. </p>
<h2>Privacy Policy, Registration Data &amp;  Member Account Security</h2>
<p>The  site respects your privacy and permits you to control the treatment of your  personal information. A complete statement of the site�s current privacy policy  can be found by <a href="LinktoPrivacyPolicy">clicking here</a>. </p>
When you are  required to open an account to use or access the site or service, you must  complete the registration process by providing the complete and accurate  information requested on the registration form.�  In consideration of your use of the site, you agree to: (a) provide  accurate, current and complete information about you as may be prompted by any  registration forms on the site (&quot;Registration Data&quot;); (b) maintain  the security of your password and identification; (c) maintain and promptly  update the Registration Data, and any other information you provide, to keep it  accurate, current and complete; and <br />
  (d) be fully  responsible for all use of your account and for any actions that take place  using your account.� In consideration of  your use of the site, you also agree to notify us immediately on any  unauthorized use of your account, user name, or password. The Company shall not  be liable for any loss that you incur as a result of someone else using your  password, either with or without your knowledge. You may be held liable for any  losses incurred by us, our affiliates, officers, directors, employees,  consultants, agents, and representatives due to someone else�s use of your  account or password. </h2>
<h2>Proprietary Rights in Site Content  &amp; Limited License</h2>
<p>GoalFace  may make certain content and software available to you from the site. If you  download content and software from the site, all content and software on the  site and available through the service, including but not limited to designs,  text, graphics, pictures, video, information, applications, software, music,  sound and other files, and their selection and arrangement (the &quot;site  Content&quot;), are the proprietary property of the Company, its users or its  licensors with all rights reserved. All trademarks and logos are owned by GoalFace  or their licensors and you may not copy or use them in any manner.� No site Content may be modified, copied,  distributed, framed, reproduced, republished, downloaded, displayed, posted,  transmitted, or sold in any form or by any means, in whole or in part, without  the Company's prior written permission, except that the foregoing does not  apply to your own User Content (as defined below) that you legally post on the  site. Provided that you meet the eligibility requirements to use the site, you  are granted a limited license to access and use the site and the site Content  and to download or print a copy of any portion of the site Content to which you  have properly gained access solely for your personal, non-commercial, home use,  provided that you keep all copyright or other proprietary notices intact.  Except for your own User Content, you may not sell, redistribute, reproduce the  site Content, nor may you recompile, reverse-engineer, disassemble, or  otherwise convert or republish the site Content to any Internet, Intranet or  Extranet site or incorporate the information in any other database or  compilation. Such license is subject to these Terms of Service and does not  include use of any data mining, robots or similar data gathering or extraction  methods. Any use of the site or the site Content other than as specifically  authorized herein, without the prior written permission of Company, is strictly  prohibited and will terminate the license granted herein. Such unauthorized use  may also violate applicable laws including without limitation copyright and  trademark laws and applicable communications regulations and statutes. Unless  explicitly stated herein, nothing in these Terms of Service shall be construed  as conferring any license to intellectual property rights, whether by stopple,  implication or otherwise. This license is revocable at any time without notice  and with or without cause.</p>
<h2>Trademarks</h2>
<p>GOALFACE,  GAMETALK, COMMUNITY PULSE, company graphics, tag line, logos, designs, page  headers, button icons, scripts and service names are trademarks and  servicemarks of the Company in the U.S. and/or other countries.  Company's trademarks and servicemarks may not be used, including as part of  trademarks and/or as part of domain names, in connection with any product or  service in any manner that is likely to cause confusion and may not be copied,  imitated, or used, in whole or in part, without the prior written permission of  the Company. </p>
<h2>User Conduct</h2>
<p>You  understand that except for advertising programs offered by us on the site, the  service and the site are available for your personal, non-commercial use only.  You represent, warrant and agree that no materials of any kind submitted  through your account or otherwise posted, transmitted, or shared by you on or  through the service will violate or infringe upon the rights of any third  party, including copyright, servicemark, trademark, privacy, publicity or other  personal or proprietary rights; or contain libelous, defamatory, hateful, or  otherwise unlawful material. <br />
    <br />
  In  addition, you agree not to use the service or the site to: </p>
<ul type="disc">
  <li>harvest or collect email addresses or other contact information of other users from the service or       the site by electronic or other means for the purposes of sending       unsolicited emails or other unsolicited communications;</li>
  <li>use the service or the site in any unlawful manner or in any other manner that could damage, disable,       overburden or impair the site;</li>
  <li>use automated scripts to collect data and/or information from or otherwise interact with the       service or the site;</li>
  <li>upload, post, transmit, share, store or otherwise make available any content that we deem to be       harmful, threatening, unlawful, defamatory, infringing, abusive,       inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy       or publicity rights, hateful, or racially, ethnically or otherwise       objectionable; </li>
  <li>upload, post, transmit, share, store or otherwise make available any content including, but not       limited to, pictures and videos other than those of a personal nature       that: (i) are taken       by you, (ii) are original art or animation created by you or your friends       (iii) are of a topic and subject matter relevant to and appropriate for       GoalFace members;</li>
  <li>register for more than one User account, register for a User account on behalf of an individual other       than yourself, or register for a User account on behalf of any group or       entity;</li>
  <li>impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or       your affiliation with any person or entity; </li>
  <li>upload, post, transmit, share or otherwise make available any unsolicited or unauthorized advertising,       solicitations, promotional materials, &quot;junk mail,&quot;       &quot;spam,&quot; &quot;chain letters,&quot; &quot;pyramid schemes,&quot;       or any other form of solicitation; </li>
  <li>upload, post, transmit, share, store or otherwise make publicly available on the site any private       information of any third party, including, without limitation, addresses,       phone numbers, email addresses, Social Security numbers and credit card       numbers;</li>
  <li>solicit personal information from anyone under 18 or solicit passwords or personally identifying       information for commercial or unlawful purposes;</li>
  <li>upload, post, transmit, share or otherwise make available any material that contains software       viruses or any other computer code, files or programs designed to interrupt,       destroy or limit the functionality of any computer software or hardware or       telecommunications equipment; </li>
  <li>intimidate or harass another; </li>
  <li>upload, post, transmit, share, store or otherwise make available content that would constitute,       encourage or provide instructions for a criminal offense, violate the       rights of any party, or that would otherwise create liability or violate       any local, state, national or international law;</li>
  <li>use or attempt to use another's account, service or system without authorization from the       Company, or create a false identity on the service or the site.</li>
  <li>upload, post, transmit,share, store or otherwise make available content that, in the sole       judgment of Company, is objectionable or which restricts or inhibits any       other person from using or enjoying the site, or which may expose Company       or its users to any harm or liability of any type.</li>
</ul>
<p>Without  limiting any of the foregoing, you also agree to abide by our �Rules of the Game� that provides  further information regarding the authorized conduct of users on GoalFace.<br />
    <strong>SPECIAL  ADMONITIONS FOR INTERNATIONAL USE</strong><br />
  Recognizing  the global nature of the Internet, you agree to comply with all local rules  regarding online conduct and acceptable Content. Specifically, you agree to  comply with all applicable laws regarding the transmission of technical data  exported from the United    States and/or the country in which you  reside. <br />
  <strong>NO  THIRD-PARTY BENEFICIARIES</strong> <br />
  You  agree that, except as otherwise expressly provided in this Terms of Service,  there shall be no third-party beneficiaries to this agreement. <br />
  <strong>NOTICE<br />
</strong>Company  may provide you with notices, including those regarding changes to the Terms of  Service, by email, regular mail or postings on the site.</p>
<h2>User Content Posted on the site</h2>
<p>You  are solely responsible for the photos, profiles, messages, notes, text,  information, music, video, advertisements, listings, and other content that you  upload, publish or display (hereinafter, &quot;post&quot;) on or through the  service or the site, or transmit to or share with other users (collectively the  &quot;User Content&quot;). Whenever you upload material to the site, or use the  site to make contact with other users of the site you shall be solely  responsible for your own User Content and the consequences of uploading it. You  may not post, transmit, or share User Content on the site or service that you  did not create or that you do not have permission to post. You warrant,  represent and undertake that: (i) you own or have the necessary licences,  rights, consents and permissions to use and authorize Company to use all  patent, trademark, trade secret, copyright or other proprietary rights in and  to any and all User Content to enable inclusion and use of the User Content in  the manner contemplated by the site and these Terms of Service; and (ii) you  have the written consent, release, and/or permission of each and every  identifiable individual person in any User Content to use the name or likeness  of each and every such identifiable individual person to enable inclusion and  use of the User Content in the manner contemplated by the site and service and  these Terms of Service. You understand and agree that the Company may, but is  not obligated to, review the site and may delete or remove (without notice) any  site Content or User Content in its sole discretion, for any reason or no  reason, including without limitation User Content that in the sole judgment of  the Company violates this Agreement or Rules of the Game (User Guidelines), which might  be offensive, illegal, or that might violate the rights, harm, or threaten the  safety of users or others. You are solely responsible at your sole cost and  expense for creating backup copies and replacing any User Content you post or  store on the site or provide to the Company. <br />
    <br />
  When you  post User Content to the site, you authorize and direct us to make such copies  thereof as we deem necessary in order to facilitate the posting and storage of  the User Content on the site. By posting User Content to any part of the site,  you automatically grant, and you represent and warrant that you have the right  to grant, to the Company an irrevocable, perpetual, non-exclusive,  transferable, fully paid, worldwide license (with the right to sublicense) to  use, copy, publicly perform, publicly display, reformat, translate, excerpt (in  whole or in part) and distribute such User Content for any purpose on or in  connection with the site or the promotion thereof, to prepare derivative works  of, or incorporate into other works, such User Content, and to grant and  authorize sublicenses of the foregoing. You may remove your User Content from  the site at any time. If you choose to remove your User Content, the license  granted above will automatically expire, however you acknowledge that the  Company may retain archived copies of your User Content.</p>
<h2>GoalFace  Mobile services</h2>
<p>The service includes certain services  that are available via your mobile phone, including (i) the ability to upload  content to GoalFace via your mobile phone (Mobile Uploads), (ii) the ability to  receive and reply to GoalFace messages, to view and post to the Community  Pulse, write Goooalshouts or receive Goooalshouts using text messaging (Mobile  Texts), (iii) the ability to browse GoalFace from your mobile phone (Mobile  Web), and (iv) the ability to access certain GoalFace features through a mobile  application you have downloaded and installed on your mobile phone (Mobile  Client) (collectively the &quot;Mobile services&quot;). We do not charge for  these Mobile services. However, your carrier's  normal messaging, data and other rates and fees will still apply. You should  check with your carrier to find out what plans are available and how much they  cost. In addition, downloading, installing, or using certain Mobile services  may be prohibited or restricted by your carrier, and not all Mobile  services may work with all carriers or devices. Therefore, you should check  with your carrier to find out if the Mobile services are available for your  mobile devices, and what restrictions, if any, may be applicable to your use of  such Mobile services. By using the Mobile  services, you agree that we may communicate with you regarding GoalFace and  other entities by SMS, MMS, text message or other electronic means to your  mobile device and that certain information  about your usage of the Mobile services may be  communicated to us. </p>
<h2>Copyright Infringement</h2>
<p>We  respect the intellectual property rights of others and we prohibit users from  uploading, posting or otherwise transmitting on the GoalFace site or service  any materials that violate another party's intellectual property rights. We  have adopted a policy that provides for the immediate suspension and/or  termination of any site or service user who repeatedly infringes on the rights  of GoalFace or of a third party, or otherwise violated any intellectual property  laws or regulations. GoalFace�s policy is to investigate any allegations of  copyright infringement brought to its attention. If you have evidence, know, or  have a good faith belief that your rights or the rights of a third party have  been violated and you want GoalFace to delete, edit, or disable the material in  question, you must provide GoalFace with the following: <br />
  (a) a physical or electronic signature of a person authorized to act on behalf  of the owner of the exclusive right that is allegedly infringed; (b)  identification of the copyrighted work claimed to have been infringed, or, if  multiple copyrighted works are covered by a single notification, a  representative list of such works; (c) identification of the material that is  claimed to be infringed or to be the subject of infringing activity and that is  to be removed or access to which is to be disabled, and information reasonably  sufficient to permit GoalFace to locate the material; (d) information  reasonably sufficient to permit GoalFace to contact you, such as an address,  telephone number, and if available, an electronic mail address at which you may  be contacted; (e) a statement that you have a good faith belief that use of the  material in the manner complained of is not authorized by the copyright owner,  its agent, or the law; and (f) a statement that the information in the  notification is accurate, and under penalty of perjury, that you are authorized  to act on behalf of the owner of an exclusive right that is allegedly  infringed. For this notification to be effective, you must provide it to  GoalFace�s designated agent at: <br />
  <br />
  GoalFace Copyright Infringement <br />
  c/o VG Media Group LLC We should  check to see what others are doing� but I have noticed that some have the  letters sent to their attorneys<br />
  FAX: <br />
  EMAIL:  <a href="mailto:communitymanager@goalface.com">communitymanager@goalface.com</a></p>
<h2>Repeat Infringement Policy</h2>
<p>In  accordance with the Digital Millennium Copyright Act (DMCA) and other  applicable law, the Company has adopted a policy of terminating, in appropriate  circumstances and at Company's sole discretion, members who have or are deemed  to have committed repeat infringement. Company may also at its sole discretion  limit access to the site and/or terminate the memberships of any users who  infringe any intellectual property rights of others, whether or not there is  any repeat infringement.</p>
<h2><strong>Links</strong> to  Third Party Websites and Content</h2>
<p>The  site contains (or you may be sent through the site or the service) links to  other web sites (&quot;Third Party sites&quot;) as well as articles,  photographs, text, graphics, pictures, designs, music, sound, video,  information, applications, software and other content or items belonging to or  originating from third parties (the &quot;Third Party Applications, Software or  Content&quot;). Such Third Party sites and Third Party Applications, Software  or Content are not investigated, monitored or checked for accuracy,  appropriateness, or completeness by us, and we are not responsible or liable  and we do not endorse any Third Party sites accessed through the site or any  Third Party Applications, Software or Content posted on, available through or  installed from the site, including without limitation the content, advertising,  accuracy, offensiveness, opinions, reliability, privacy practices or other  policies of or contained in the Third Party sites or the Third Party  Applications, Software or Content. Inclusion of, linking to or permitting the  use or installation of any Third Party site or any Third Party Applications,  Software or Content does not imply approval or endorsement thereof by us. If  you decide to leave the site and access the Third Party sites or to use or  install any Third Party Applications, Software or Content, you do so at your  own risk and you should be aware that our terms and policies no longer govern.  You should review the applicable terms and policies, including privacy and data  gathering practices, of any site to which you navigate from the site or  relating to any applications you use or install from the site.</p>
<h2>Share service</h2>
<p>Company  offers a feature whereby users of the site can forward and/or share with others  or post to their own member profile, videos, articles and other Third Party  Applications, Software or Content from, and/or links to, Third Party sites  through the service (the &quot;Share service&quot;). You acknowledge and agree  that your use of the Share services and all links, User Content or Third Party  Applications, Software or Content sent or shared through the Share service is  subject to, and will fully comply with the user conduct rules set forth above  and the other terms and conditions set forth in these Terms of Service.</p>
<h2>Use of  Share Links by Online Content Providers</h2>
<p>Subject to the terms and conditions of these  Terms of Service, Third Party sites that meet the requirements set forth below  may place a Share Link (as described below), in the form approved by Company,  on pages of their web sites to facilitate use of the Share service. A Third  Party site that posts a Share Link on its web site is referred to herein as an  &quot;Online Content Provider&quot; and shall abide and be subject to the  applicable sections of these Terms of Service. A &quot;Share Link&quot; is a  button and/or a text link appearing on an Online Content Provider's web page  that, upon being clicked by a user, enables us to launch a sharing mechanism  through which users can share with others or post to their own member profile,  links and content from that page. <br />
    <br />
  In the event that the Share Link is a button  that contains any icons or other graphic images, trademarks or other  proprietary materials of the Company, Online Content Provider is granted  permission to use such images, trademarks or other materials solely for the  purpose of placing the Share Link on Online Content Provider's site and solely  in the current form provided by the Company. In the event that the Share Link is  a text link, it must include the word &quot;GoalFace&quot; as part of the link.  The rights granted in this paragraph may be revoked by Company at any time with  or without cause in its sole discretion, and upon such termination, Online  Content Provider agrees to immediately remove all Share Links from its site. <br />
  <br />
  In order for an Online Content Provider to  include a Share Link on its pages, the Third Party site must not contain any  web content that if shared or posted by a user would be a violation of the user  conduct rules set forth above. Without limiting the forgoing, Online Content  Provider agrees not to post a Share Link on any web site that contains, and  represents and warrants that such web site does not and will not contain, any  content that is infringing, harmful, threatening, unlawful, defamatory,  abusive, inflammatory, harassing, vulgar, obscene, lewd, fraudulent, or  invasive of privacy or publicity rights or that may expose Company or its users  to any harm or liability of any type. Upon including of a Share Link, Online  Content Provider agrees to defend, indemnify and hold the Company, its  subsidiaries and affiliates, and each of their directors, officers, agents,  contractors, partners and employees, harmless from and against any loss,  liability, claim, demand, damages, costs and expenses, including reasonable  attorney's fees, arising out of or in connection with such Share Link, any  links, content or other items or materials which may be shared or posted  through such Share Link, or any breach or alleged breach of the foregoing  representations and warranties. <br />
  <br />
  By including a Share Link, Online Content  Provider automatically grants, and represents and warrants that it has the  right to grant, to the Company an irrevocable, perpetual, non-exclusive,  transferable, fully paid, worldwide license (with the right to sublicense) to  use the Share service in order to link to, use, copy, publish, stream, publicly  perform, publicly display, reformat, translate, excerpt (in whole or in part),  summarize, and distribute the content, links and other materials of any kind  residing on any web pages on which Online Content Provider places the Share  Link. </p>
<h2><strong>DEALINGS WITH ADVERTISERS AND  MERCHANTS </strong><br /></h2>
  Your  correspondence or business dealings with, or participation in promotions of,  any advertisers and merchants found on or through the site and service,  including payment for and delivery of related goods or services, and any other  terms, conditions, warranties or representations associated with such dealings,  are solely between you and such advertiser or merchant. To the fullest extent  permitted by applicable law, you agree that: (a) Company shall not be  responsible or liable for any loss or damage of any kind incurred as the result  of any such dealings or as the result of the presence of such advertisers and  merchants on the site and service, and (b) any orders placed by you on, and any  product specifications and product availability appearing on, the site and  service (including, without limitation, any online store) are subject to confirmation  by, and the terms and conditions of business of the relevant advertiser or  merchant. </h2>
<h2>GoalFace Marketplace</h2>
<p>All  listings posted on or through the GoalFace Marketplace service and all  transactions conducted in connection therewith are subject to and governed by  the <a href="http://register.facebook.com/marketplace/guidelines.php">GoalFace Marketplace  Guidelines</a> (the &quot;Guidelines&quot;) as well as these Terms  of Use. When you use GoalFace Marketplace in any manner you are agreeing to  abide by and be subject to the Guidelines and the other applicable rules set  forth in these Terms of Use. The Guidelines are subject to change without prior  notice at any time, in the Company's sole discretion, so you should review the  Guidelines each time you use GoalFace Marketplace. Parties to a transaction are  solely responsible for all interactions with each other, for arranging for  payment and the exchange of the goods or services purchased if applicable, and  for the results and performance of any transaction or relationship entered into  through GoalFace Marketplace. You acknowledge that GoalFace is not responsible  or liable for any action or inaction of any party to a transaction, for any  failure to perform, to pay any amounts due, or to deliver any merchandise or  services as promised, or for any other aspect of the transaction. Any fees or  payments collected by GoalFace applicable to GoalFace Marketplace are set forth  on the site, and all terms and conditions applicable to such fees are set forth  in the <a href="http://register.facebook.com/termsofsale.php">GoalFace Terms of Sale</a> However, please note  that the Terms of Sale do not apply to your purchases of products or services  from third parties through GoalFace Marketplace, as those transactions are  strictly between you and the other party to the transaction. ALL USE OF  GOALFACE MARKETPLACE IS PROVIDED &quot;AS IS&quot; AND AT YOUR OWN RISK.</p>
<h2>Terms of Sale</h2>
<p>Please  refer to our <a href="http://register.facebook.com/termsofsale.php">Terms of Sale</a> for the terms,  conditions and policies applicable to your purchase of products or services  from Company. By ordering products or services from Company through the site,  you agree to be bound by and accept the Terms of Sale. The Terms of Sale are  subject to change without prior notice at any time, in Company's sole  discretion so you should review the Terms of Sale each time you make a  purchase. </p>
<h2>User Disputes</h2>
<p>You  are solely responsible for your interactions with other GoalFace users. We  reserve the right, but have no obligation, to monitor disputes between you and  other users.</p>
<h2>Privacy</h2>
<p>We  care about the privacy of our users. Click  here to view the  GoalFace's Privacy Policy. By using the site or the service, you are consenting  to have your personal data transferred to and processed in the United States.</p>
<h2>Disclaimers</h2>
<p>The  Company is not responsible or liable in any manner for any User Content or  Third Party Applications, Software or Content posted on the site or in  connection with the service, whether posted or caused by users of the site, by  GoalFace, by third parties or by any of the equipment or programming associated  with or utilized in the site or the service. Although we provide rules for user  conduct and postings, we do not control and are not responsible for what users  post, transmit or share on the site and are not responsible for any offensive,  inappropriate, obscene, unlawful or otherwise objectionable content you may  encounter on the site or in connection with any User Content or Third Party  Applications, Software or Content. The Company is not responsible for the  conduct, whether online or offline, of any user of the site or service. <br />
    <br />
  The site  and the service may be temporarily unavailable from time to time for  maintenance or other reasons. Company assumes no responsibility for any error,  omission, interruption, deletion, defect, delay in operation or transmission,  communications line failure, theft or destruction or unauthorized access to, or  alteration of, User communications. The Company is not responsible for any  technical malfunction or other problems of any telephone network or service,  computer systems, servers or providers, computer, mobile phone or other  electronic equipment, software, failure of email or players on account of  technical problems or traffic congestion on the Internet or at any site or  combination thereof, including injury or damage to User's or to any other  person's computer, mobile phone, or other hardware or software, related to or  resulting from using or downloading materials in connection with the Web and/or  in connection with the service, including without limitation any Mobile Client  software. Under no circumstances will the Company be responsible for any loss  or damage, including any loss or damage to any User Content or personal injury  or death, resulting from anyone's use of the site or the service, any User  Content or Third Party Applications, Software or Content posted on or through  the site or the service or transmitted to Users, or any interactions between  users of the site, whether online or offline. <br />
  <br />
  THE  SITE, THE SERVICE, ANY PLATFORM APPLICATIONS AND THE SITE CONTENT ARE PROVIDED  &quot;AS-IS&quot; AND THE COMPANY DISCLAIMS ANY AND ALL REPRESENTATIONS AND  WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED  WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR  NON-INFRINGEMENT. THE COMPANY CANNOT GUARANTEE AND DOES NOT PROMISE ANY  SPECIFIC RESULTS FROM USE OF THE SITE AND/OR THE SERVICE AND/OR ANY PLATFORM  APPLICATIONS. COMPANY DOES NOT REPRESENT OR WARRANT THAT SOFTWARE, CONTENT OR  MATERIALS ON THE SITE, THE SERVICE OR ANY PLATFORM APPLICATIONS ARE ACCURATE,  COMPLETE, RELIABLE, CURRENT OR ERROR-FREE OR THAT THE SITE OR SERVICE ITS  SERVERS, OR ANY PLATFORM APPLICATIONS ARE FREE OF VIRUSES OR OTHER HARMFUL  COMPONENTS. THEREFORE, YOU SHOULD EXERCISE CAUTION IN THE USE AND DOWNLOADING  OF ANY SUCH SOFTWARE, CONTENT OR MATERIALS AND USE INDUSTRY-RECOGNIZED SOFTWARE  TO DETECT AND DISINFECT VIRUSES. WITHOUT LIMITING THE FOREGOING, YOU UNDERSTAND  AND AGREE THAT YOU DOWNLOAD OR OTHERWISE OBTAIN CONTENT, MATERIAL, DATA OR  SOFTWARE (INCLUDING ANY MOBILE CLIENT) FROM OR THROUGH THE SERVICE AND ANY  PLATFORM APPLICATIONS AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE  SOLELY RESPONSIBLE FOR YOUR USE THEREOF AND ANY DAMAGES TO YOUR MOBILE DEVICE  OR COMPUTER SYSTEM, LOSS OF DATA OR OTHER HARM OF ANY KIND THAT MAY RESULT. <br />
  <br />
  The  Company reserves the right to change any and all content, software and other  items used or contained in the site and any services and Platform Applications  offered through the site at any time without notice. Reference to any products,  services, processes or other information, by trade name, trademark,  manufacturer, supplier or otherwise does not constitute or imply endorsement,  sponsorship or recommendation thereof, or any affiliation therewith, by  Company. </p>
<h2>Limitation on Liability</h2>
<p>IN NO  EVENT WILL COMPANY OR ITS DIRECTORS, EMPLOYEES OR AGENTS BE LIABLE TO YOU OR  ANY THIRD PERSON FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL,  SPECIAL OR PUNITIVE DAMAGES, INCLUDING FOR ANY LOST PROFITS OR LOST DATA  ARISING FROM YOUR USE OF THE SITE OR THE SERVICE, ANY PLATFORM APPLICATIONS OR  ANY OF THE SITE CONTENT OR OTHER MATERIALS ON, ACCESSED THROUGH OR DOWNLOADED  FROM THE SITE, EVEN IF THE COMPANY IS AWARE OR HAS BEEN ADVISED OF THE  POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED  HEREIN, THE COMPANY'S LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS  OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF  ANY, BY YOU TO COMPANY FOR THE SERVICE DURING THE TERM OF MEMBERSHIP, BUT IN NO  CASE WILL THE COMPANY'S LIABILITY TO YOU EXCEED $150. YOU ACKNOWLEDGE THAT IF  NO FEES ARE PAID TO COMPANY FOR THE SERVICE, YOU SHALL BE LIMITED TO INJUNCTIVE  RELIEF ONLY, UNLESS OTHERWISE PERMITTED BY LAW, AND SHALL NOT BE ENTITLED TO  DAMAGES OF ANY KIND FROM COMPANY, REGARDLESS OF THE CAUSE OF ACTION. <br />
    <br />
  CERTAIN  STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR  LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE  ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY  HAVE ADDITIONAL RIGHTS. </p>
<h2>Termination</h2>
<p>The  Company may terminate your membership, delete your profile and any content or  information that you have posted on the site or through any Platform  Application and/or prohibit you from using or accessing the service or the site  or any Platform Application (or any portion, aspect or feature of the service  or the site or any Platform Application) for any reason, or no reason, at any  time in its sole discretion, with or without notice, including without  limitation if it believes that you are under 13, or under 18 and not in high  school or college. When we are notified that a user has died, we will generally,  but are not obligated to, keep the user's account active under a special  memorialized status for a period of time determined by us to allow other users  to post and view comments.</p>
<h2><strong>Copyright</strong>. <br /></h2>
  All contents  of site or service are Copyright � 2008 GoalFace Inc. All rights reserved. </h2>
<h2>Governing Law, Venue and Jurisdiction</h2>
  By visiting or  using the site and/or the service, you agree that the laws of the State of Virginia, without regard  to principles of conflict of laws, will govern these Terms of Service and any  dispute of any sort that might arise between you and the Company or any of our  affiliates. With respect to any disputes or claims not subject to arbitration  (as set forth below), you agree not to commence or prosecute any action in  connection therewith other than in the state and federal courts of Virginia,  and you hereby consent to, and waive all defenses of lack of personal  jurisdiction and forum non conveniens with respect to, venue and jurisdiction  in the state and federal courts of Virginia. </h2>
<h2>Arbitration</h2>
  YOU AND  COMPANY AGREE THAT, EXCEPT AS MAY OTHERWISE BE PROVIDED IN REGARD TO SPECIFIC  SERVICES ON THE SITE IN ANY SPECIFIC TERMS APPLICABLE TO THOSE SERVICES, THE  SOLE AND EXCLUSIVE FORUM AND REMEDY FOR ANY AND ALL DISPUTES AND CLAIMS  RELATING IN ANY WAY TO OR ARISING OUT OF THESE TERMS OF SERVICE, THE SITE  AND/OR THE SERVICE (INCLUDING YOUR VISIT TO OR USE OF THE SITE AND/OR THE  SERVICE) SHALL BE FINAL AND BINDING ARBITRATION, except that: (a) to the extent  that either of us has in any manner infringed upon or violated or threatened to  infringe upon or violate the other party's patent, copyright, trademark or  trade secret rights, or you have otherwise violated any of the user conduct  rules set forth above or in the Code of Conduct then the parties acknowledge  that arbitration is not an adequate remedy at law and that injunctive or other  appropriate relief may be sought; and (b) no disputes or claims relating to any  transactions you enter into with a third party through the site may be  arbitrated. <br />
  <br />
  Arbitration  under this Agreement shall be conducted by the American Arbitration Association  (the &quot;AAA&quot;) under its Commercial Arbitration Rules and, in the case  of consumer disputes, the AAA's Supplementary Procedures for Consumer Related  Disputes ( the &quot;AAA Consumer Rules&quot;) (collectively the &quot;AAA  Rules&quot;). The location of the arbitration and the allocation of costs and  fees for such arbitration shall be determined in accordance with such AAA Rules  and shall be subject to the limitations provided for in the AAA Consumer Rules  (for consumer disputes). If such costs are determined to be excessive in a  consumer dispute, the Company will be responsible for paying all arbitration  fees and arbitrator compensation in excess of what is deemed reasonable. The  arbitrator's award shall be binding and may be entered as a judgment in any  court of competent jurisdiction. <br />
  <br />
  To the fullest  extent permitted by applicable law, NO ARBITRATION OR CLAIM UNDER THESE TERMS  OF SERVICE SHALL BE JOINED TO ANY OTHER ARBITRATION OR CLAIM, INCLUDING ANY  ARBITRATION OR CLAIM INVOLVING ANY OTHER CURRENT OR FORMER USER OF THE SERVICE,  AND NO CLASS ARBITRATION PROCEEDINGS SHALL BE PERMITTED. In no event shall any  claim, action or proceeding by you related in any way to the site and/or the  service (including your visit to or use of the site and/or the service) be  instituted more than three (3) years after the cause of action arose. </h2>
<h2>Indemnity</h2>
  You agree to  indemnify and hold the Company, its subsidiaries and affiliates, and each of  their directors, officers, agents, contractors, partners and employees,  harmless from and against any loss, liability, claim, demand, damages, costs  and expenses, including reasonable attorney's fees, arising out of or in  connection with any User Content, any Third Party Applications, Software or  Content you post or share on or through the site (including without limitation  through the Share service), your use of the service or the site, your conduct  in connection with the service or the site or with other users of the service  or the site, or any violation of this Agreement or of any law or the rights of  any third party. </h2>
<h2>Submissions</h2>
  You  acknowledge and agree that any questions, comments, suggestions, ideas,  feedback or other information about the site or the service (&quot;Submissions&quot;),  provided by you to Company are non-confidential and shall become the sole  property of Company. Company shall own exclusive rights, including all  intellectual property rights, and shall be entitled to the unrestricted use and  dissemination of these Submissions for any purpose, commercial or otherwise,  without acknowledgment or compensation to you. </h2>
<h2>SEVERABILITY WAIVER</h2>
  If, for  whatever reason, a court of competent jurisdiction finds any term or condition  in these Terms of Service to be unenforceable, all other terms and conditions  will remain unaffected and in full force and effect. No waiver of any breach of  any provision of these Terms of Service shall constitute a waiver of any prior,  concurrent, or subsequent breach of the same or any other provisions hereof,  and no waiver shall be effective unless made in writing and signed by an  authorized representative of the waiving party.</h2>
<p><strong>NO  LICENSE</strong>. <br />
  Nothing  contained on the site should be understood as granting you a license to use any  of the trademarks, service marks, or logos owned by GoalFace or by any third  party.</p>
<h2>Questions</h2>
  Please visit  our <a href="/help">Help</a> page for more information </h2>
<p><strong>Other<br />
  </strong>These  Terms of Service constitute the entire agreement between you and Company  regarding the use of the site and/or the service, superseding any prior  agreements between you and Company relating to your use of the site or the  service. The failure of Company to exercise or enforce any right or provision  of these Terms of Service shall not constitute a waiver of such right or provision.<br />
  <h2><strong>ACKNOWLEDGEMENT</strong>. </h2>
  BY USING  THE SERVICE OR ACCESSING THE SITE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE  TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.</p>



</div>

