<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
<title><?php echo $this->escape($this->title); ?></title>
<meta name='description' content="<?php echo $this->escape($this->description); ?>" />
<meta name='keywords' content="<?php echo $this->escape($this->keywords); ?>" />
<link href='<?php echo Zend_Registry::get("contextPath"); ?>/public/styles/goalface.css' rel="stylesheet" type="text/css" media="screen"/>
</head>

<body  Zbody class="home">
<div id="wrapper">

    <!--Starts Header-->
      <div id="LogoGlobalNav">
 		<a href="/" class="logo"><img src="<?php echo Zend_Registry::get("contextPath"); ?>/public/images/logo.gif"></a>
         <div style="position:absolute;left:290px;top:6px;">
              Join the fun. Connect with football fans around the world.
              <a href="<?php echo Zend_Registry::get("contextPath"); ?>/user/register">Become a member now It's Free.</a>
            </div>
    	    <div>

    			<a href="<?php echo Zend_Registry::get("contextPath"); ?>/login" title="Sign In"> Sign In</a>
                |
    			<a href="<?php echo Zend_Registry::get("contextPath"); ?>/options/help" title="GoalFace Help">Help</a>
    			
    			<form method="get" action="#">
    			  <fieldset>
    				<input type="text" name="q" id="search-query" />
    				<input type="submit" value="Search" class="submit">
    			  </fieldset>
    			</form>
            </div>
      </div>
       <!--End Header-->

      <div id="FormWrapper">

        <div id="FormWrapperForBottomBackground">
            <h1>Page not found</h1>

              <p>The page you were looking for could not be found.</p>

              <p>Did you get here through a link on <a href="<?php echo $_SERVER['SERVER_NAME']; ?>/index">goalface</a>? Then please <a href="mailto:webmaster@goalface.com">notify us</a> of the issue.</p>

              <h2>Search</h2>

              <p>Try finding what you were looking for by performing a search.</p>

        </div>
      </div>


	
  </div><!--end wrapper-->
</body>
</html>