<script language = "javascript">

	function nextpage(url){

   jQuery('#fullscoreboardcontent').html("<div class='ajaxloadscores'></div>");
   jQuery('#fullscoreboardcontent').load(url);
	
	}

</script>


<?php #if ($this->pageCount > 1): ?>

<div class="pagination fullscoreboard">
    <span class="numberofpage"><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>&nbsp;
			of <?php echo $this->totalItemCount; ?></span>
			<ul>
        <!-- Previous page link -->
        <li class="pre">
        <?php if (isset($this->previous)): ?>
          <a href="javascript:nextpage('<?php echo $this->url(array('page' => $this->previous)); ?>')">
            &lt;&nbsp;&nbsp;Previous
          </a>
          <?php else: ?>
          <a class="disable">
            &lt;&nbsp;&nbsp;Previous
          </a>
          <?php endif; ?>       
        </li>
        
        <?php foreach ($this->pagesInRange as $page): ?>
          <?php if ($page != $this->current): ?>      
            <li><a href="javascript:nextpage('<?php echo $this->url(array('page' => $page)); ?>')"><?php echo $page; ?></a></li>         
          <?php else: ?>
            <li><a class="current"><?php echo $page; ?></a></li>                
          <?php endif; ?>
            <li>|</li>  
        <?php endforeach; ?>
        
        <!-- Next page link -->
        <li class="next">
        <?php if (isset($this->next)): ?>
          <a href="javascript:nextpage('<?php echo $this->url(array('page' => $this->next)); ?>')">Next &gt;</a>
        <?php else: ?>
          <a class="disable">
            Next &gt;
          </a>
        <?php endif; ?>
        </li>
    </ul>
</div>  

<?php #endif; ?>               
              
             
