<?php if ($this->pageCount > 1): ?>

<li class="Pager">
         <!-- Previous page link -->
		<?php if (isset($this->previous)): ?>
		  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
		    &lt; Previous
		  </a> |
		<?php else: ?>
		  <a class="disabled">« Previous</a>|
		<?php endif; ?>
              
	<?php foreach ($this->pagesInRange as $page): ?>
	  <?php if ($page != $this->current): ?>
	    <a href="<?php echo $this->url(array('page' => $page)); ?>">
	        <?php echo $page; ?>
	    </a> |
	  <?php else: ?>
	    <a class="current"><?php echo $page; ?></a> |
	  <?php endif; ?>
	<?php endforeach; ?>
            
            <!-- Next page link -->
	<?php if (isset($this->next)): ?>
	  <a class="next" href="<?php echo $this->url(array('page' => $this->next)); ?>">
	    Next &gt;
	  </a> 
	<?php else: ?>
	   Next »
	<?php endif; ?>
</li>

 <?php endif; ?>             
              
             