<script language = "javascript">

	function nextpage(url){
		jQuery('#data').html('Loading...'); 
		jQuery('#data').load(url);
	}

</script>

<?php //if ($this->pageCount > 1): ?>

      <div class="pagination_shout">
               <!-- Previous page link -->
				<?php if (isset($this->previous)): ?>
				  <a href="javascript:nextpage('<?php echo $this->url(array('page' => $this->previous)); ?>')">
				    &lt; Prev
				  </a>|
				<?php else: ?>
				  <a class="disabled">« Prev</a>|
				<?php endif; ?>
                
			<?php foreach ($this->pagesInRange as $page): ?>
			  <?php if ($page != $this->current): ?>
			    <a href="javascript:nextpage('<?php echo $this->url(array('page' => $page)); ?>')">
			        <?php echo $page; ?>
			    </a>|
			  <?php else: ?>
			    <a class="current"><?php echo $page; ?></a>|
			  <?php endif; ?>
			<?php endforeach; ?>
              
              <!-- Next page link -->
			<?php if (isset($this->next)): ?>
			  <a class="next" href="javascript:nextpage('<?php echo $this->url(array('page' => $this->next)); ?>')">
			    Next &gt;
			  </a> 
			<?php else: ?>
			   Next »
			<?php endif; ?>
   </div>
  
<?php //endif; ?>             
              
             