<script language = "javascript">

	function nextpage(url){

		jQuery('#data').html('Loading...'); 
		jQuery('#data').load(url);
	
	}

</script>
<?php #if ($this->pageCount > 1): ?>
<ul class="Pager">
<li class="leftwider">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>&nbsp;
of <?php echo $this->totalItemCount; ?>
</li>

<li class="PageLinks">
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="javascript:nextpage('<?php echo $this->url(array('page' => $page)); ?>')">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>
</li>
<li class="PrevNext">
<!-- First page link -->
<?php /*if (isset($this->previous)): ?>
  <a href="javascript:nextpage('<?php echo $this->url(array('page' => $this->first)); ?>')">
    First
  </a> |
<?php else: ?>
  <span class="disabled">First</span> |
<?php endif; */?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="javascript:nextpage('<?php echo $this->url(array('page' => $this->previous)); ?>')">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="javascript:nextpage('<?php echo $this->url(array('page' => $this->next)); ?>')">
    Next &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Next &gt;</span> |
<?php endif; ?>

<!-- Last page link -->
<?php /*if (isset($this->next)): ?>
  <a href="javascript:nextpage('<?php echo $this->url(array('page' => $this->last)); ?>')">
    Last
  </a>
<?php else: ?>
  <span class="disabled">Last</span>
<?php endif; */?>
</li>
</ul>
<?php #endif; ?>